Sheet content can now be set by using a `DataTemplate`
DIPSAS/DIPS.Xamarin.UI pull request #225
Opened 2020-08-25 15:48 UTC by haavamoa

## Added / Fixed

- Sheet content can now be set by using a `DataTemplate`
    - The sheet content will be lazily loaded when the sheet opens and closes.
    - The sheet content view will get destroyed and recreated each time the sheet opens / closes
    - You can benefit from `x:DataType` (compiled bindings) which increases performance.

## Todo List

- [ ] I have tested on an Android device.
- [ ] I have tested on an iOS device.
- [ ] I have added unit tests

>*Please add pictures / Gifs if possible*
>*Todo List can be checked by putting a `X` inside the brackets*
>*Remember to update our `wiki` after this PR is merged*

2020-08-25 17:18 UTC, haavamoa commented on src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml.cs
> +        public InsideSheetViewModel InsideSheetViewModel => new InsideSheetViewModel();
Added for testing will remove

2020-09-07 21:12 UTC, Illedan submitted a review, later dismissed

2020-09-07 21:24 UTC, Illedan requested changes

2020-09-07 21:24 UTC, Illedan commented on src/Samples/DIPS.Xamarin.UI.Samples/Controls/Sheet/SheetPage.xaml.cs
> +        }
Remove?

2020-09-07 21:32 UTC, Illedan approved these changes

2020-09-07 21:34 UTC, merged